In [1]:
import numpy as np

In [2]:
ar = np.random.randint(1, 100, size=(6, 8))
ar

array([[23,  5, 21, 76, 73, 13, 26, 61],
       [ 3, 24, 84, 59, 82,  5, 10, 44],
       [59, 19, 31, 25, 59, 22, 85,  4],
       [12, 71, 52, 54, 48, 99, 80, 23],
       [92,  6, 24,  7, 75, 88, 61, 26],
       [ 1, 29, 62, 91, 30, 21, 31, 60]])

## Array Attributes:

In [3]:
ar.ndim

2

In [4]:
ar.shape

(6, 8)

In [5]:
ar.size

48

In [6]:
ar.dtype

dtype('int32')

In [7]:
# the size of bytes of each element in the array
ar.itemsize

4

In [8]:
ar.data

In [9]:
type(ar)

numpy.ndarray

## Array Creation:

#### 1. From a python list / tuple:

In [10]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

#### 2. seqeunces of sequences to nD arrays:

In [11]:
a2d = np.array([(1, 2, 3), (4, 5, 6)])
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                [[11, 12, 13], [14, 15, 16], [17, 18, 19]]])
a3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

#### 3. Unknown elements / known size:

In [13]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
c = np.ones((3, 4), dtype=np.int8)
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [15]:
d = np.empty((6, 3))
d

array([[1.13766012e-311, 4.84184333e-322, 0.00000000e+000],
       [0.00000000e+000, 6.23058028e-307, 1.15998412e-028],
       [2.44171989e+232, 8.00801729e+159, 6.19319847e-071],
       [5.46814361e-095, 6.01347002e-154, 1.05190656e-153],
       [4.56295599e-144, 2.86530729e+161, 8.93176633e+271],
       [4.98131536e+151, 1.47916532e-071, 8.34451504e-308]])

In [16]:
d.dtype

dtype('float64')

#### 4. Sequences of numbers - arange / linspace:

######          arange:

In [17]:
e = np.arange(10, 30, 5)
e

array([10, 15, 20, 25])

###### linspace:

In [18]:
f = np.linspace(0, 2, 9)
f

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

See also: __array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, fromfunction, fromfile, numpy.random.Generator.rand, numpy.random.Generator.randn__

## Printing Arrays:

In [19]:
# prints just corners
g = np.arange(2500).reshape(50, 50)
g

array([[   0,    1,    2, ...,   47,   48,   49],
       [  50,   51,   52, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  147,  148,  149],
       ...,
       [2350, 2351, 2352, ..., 2397, 2398, 2399],
       [2400, 2401, 2402, ..., 2447, 2448, 2449],
       [2450, 2451, 2452, ..., 2497, 2498, 2499]])

In [20]:
# prints all:
import sys
np.set_printoptions(threshold=sys.maxsize)
g

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
          22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
          33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
          44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
          61,   62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
          72,   73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
          83,   84,   85,   86,   87,   88,   89,   90,   91,   92,   93,
          94,   95,   96,   97,   98,   99],
       [ 100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
         111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
         122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
         133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
         144,  145,  146,  147,  148,  149],
       [ 150,  151,  152,  153,  154,  155,  156,  157,  158,  159,  160,
         161,  162,  163,  164,  165,  166,  167,  168,  169,  170,  171,
         172,  173,  174,  175,  176,  177,  178,  179,  180,  181,  182,
         183,  184,  185,  186,  187,  188,  189,  190,  191,  192,  193,
         194,  195,  196,  197,  198,  199],
       [ 200,  201,  202,  203,  204,  205,  206,  207,  208,  209,  210,
         211,  212,  213,  214,  215,  216,  217,  218,  219,  220,  221,
         222,  223,  224,  225,  226,  227,  228,  229,  230,  231,  232,
         233,  234,  235,  236,  237,  238,  239,  240,  241,  242,  243,
         244,  245,  246,  247,  248,  249],
       [ 250,  251,  252,  253,  254,  255,  256,  257,  258,  259,  260,
         261,  262,  263,  264,  265,  266,  267,  268,  269,  270,  271,
         272,  273,  274,  275,  276,  277,  278,  279,  280,  281,  282,
         283,  284,  285,  286,  287,  288,  289,  290,  291,  292,  293,
         294,  295,  296,  297,  298,  299],
       [ 300,  301,  302,  303,  304,  305,  306,  307,  308,  309,  310,
         311,  312,  313,  314,  315,  316,  317,  318,  319,  320,  321,
         322,  323,  324,  325,  326,  327,  328,  329,  330,  331,  332,
         333,  334,  335,  336,  337,  338,  339,  340,  341,  342,  343,
         344,  345,  346,  347,  348,  349],
       [ 350,  351,  352,  353,  354,  355,  356,  357,  358,  359,  360,
         361,  362,  363,  364,  365,  366,  367,  368,  369,  370,  371,
         372,  373,  374,  375,  376,  377,  378,  379,  380,  381,  382,
         383,  384,  385,  386,  387,  388,  389,  390,  391,  392,  393,
         394,  395,  396,  397,  398,  399],
       [ 400,  401,  402,  403,  404,  405,  406,  407,  408,  409,  410,
         411,  412,  413,  414,  415,  416,  417,  418,  419,  420,  421,
         422,  423,  424,  425,  426,  427,  428,  429,  430,  431,  432,
         433,  434,  435,  436,  437,  438,  439,  440,  441,  442,  443,
         444,  445,  446,  447,  448,  449],
       [ 450,  451,  452,  453,  454,  455,  456,  457,  458,  459,  460,
         461,  462,  463,  464,  465,  466,  467,  468,  469,  470,  471,
         472,  473,  474,  475,  476,  477,  478,  479,  480,  481,  482,
         483,  484,  485,  486,  487,  488,  489,  490,  491,  492,  493,
         494,  495,  496,  497,  498,  499],
       [ 500,  501,  502,  503,  504,  505,  506,  507,  508,  509,  510,
         511,  512,  513,  514,  515,  516,  517,  518,  519,  520,  521,
         522,  523,  524,  525,  526,  527,  528,  529,  530,  531,  532,
         533,  534,  535,  536,  537,  538,  539,  540,  541,  542,  543,
         544,  545,  546,  547,  548,  549],
       [ 550,  551,  552,  553,  554,  555,  556,  557,  558,  559,  560,
         561,  562,  563,  564,  565,  566,  567,  568,  569,  570,  571,
         572,  573,  574,  575,  576,  577,  578,  579,  580,  581,  582,
         583,  584,  585,  586,  587,  588,  589,  590,  591,  592,  593,
         594,  595,  596,  597,  598,  599],
       [ 600,  601,  602,  603,  604,  605,  606,  607,  608,  609,  610,
         611,  612,  613,  614,  615,  616,  617,  618,  619,  620,  621,
         622,  623,  624,  625,  626,  627,  628,  629,  630,  631,  632,
         633,  634,  635,  636,  637,  638,  639,  640,  641,  642,  643,
         644,  645,  646,  647,  648,  649],
       [ 650,  651,  652,  653,  654,  655,  656,  657,  658,  659,  660,
         661,  662,  663,  664,  665,  666,  667,  668,  669,  670,  671,
         672,  673,  674,  675,  676,  677,  678,  679,  680,  681,  682,
         683,  684,  685,  686,  687,  688,  689,  690,  691,  692,  693,
         694,  695,  696,  697,  698,  699],
       [ 700,  701,  702,  703,  704,  705,  706,  707,  708,  709,  710,
         711,  712,  713,  714,  715,  716,  717,  718,  719,  720,  721,
         722,  723,  724,  725,  726,  727,  728,  729,  730,  731,  732,
         733,  734,  735,  736,  737,  738,  739,  740,  741,  742,  743,
         744,  745,  746,  747,  748,  749],
       [ 750,  751,  752,  753,  754,  755,  756,  757,  758,  759,  760,
         761,  762,  763,  764,  765,  766,  767,  768,  769,  770,  771,
         772,  773,  774,  775,  776,  777,  778,  779,  780,  781,  782,
         783,  784,  785,  786,  787,  788,  789,  790,  791,  792,  793,
         794,  795,  796,  797,  798,  799],
       [ 800,  801,  802,  803,  804,  805,  806,  807,  808,  809,  810,
         811,  812,  813,  814,  815,  816,  817,  818,  819,  820,  821,
         822,  823,  824,  825,  826,  827,  828,  829,  830,  831,  832,
         833,  834,  835,  836,  837,  838,  839,  840,  841,  842,  843,
         844,  845,  846,  847,  848,  849],
       [ 850,  851,  852,  853,  854,  855,  856,  857,  858,  859,  860,
         861,  862,  863,  864,  865,  866,  867,  868,  869,  870,  871,
         872,  873,  874,  875,  876,  877,  878,  879,  880,  881,  882,
         883,  884,  885,  886,  887,  888,  889,  890,  891,  892,  893,
         894,  895,  896,  897,  898,  899],
       [ 900,  901,  902,  903,  904,  905,  906,  907,  908,  909,  910,
         911,  912,  913,  914,  915,  916,  917,  918,  919,  920,  921,
         922,  923,  924,  925,  926,  927,  928,  929,  930,  931,  932,
         933,  934,  935,  936,  937,  938,  939,  940,  941,  942,  943,
         944,  945,  946,  947,  948,  949],
       [ 950,  951,  952,  953,  954,  955,  956,  957,  958,  959,  960,
         961,  962,  963,  964,  965,  966,  967,  968,  969,  970,  971,
         972,  973,  974,  975,  976,  977,  978,  979,  980,  981,  982,
         983,  984,  985,  986,  987,  988,  989,  990,  991,  992,  993,
         994,  995,  996,  997,  998,  999],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021,
        1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032,
        1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043,
        1044, 1045, 1046, 1047, 1048, 1049],
       [1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060,
        1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071,
        1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082,
        1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093,
        1094, 1095, 1096, 1097, 1098, 1099],
       [1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110,
        1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121,
        1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132,
        1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143,
        1144, 1145, 1146, 1147, 1148, 1149],
       [1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160,
        1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171,
        1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182,
        1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193,
        1194, 1195, 1196, 1197, 1198, 1199],
       [1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210,
        1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221,
        1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232,
        1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243,
        1244, 1245, 1246, 1247, 1248, 1249],
       [1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260,
        1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271,
        1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282,
        1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293,
        1294, 1295, 1296, 1297, 1298, 1299],
       [1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310,
        1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321,
        1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332,
        1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343,
        1344, 1345, 1346, 1347, 1348, 1349],
       [1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360,
        1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371,
        1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382,
        1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393,
        1394, 1395, 1396, 1397, 1398, 1399],
       [1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410,
        1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421,
        1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432,
        1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443,
        1444, 1445, 1446, 1447, 1448, 1449],
       [1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460,
        1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471,
        1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482,
        1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493,
        1494, 1495, 1496, 1497, 1498, 1499],
       [1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510,
        1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521,
        1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532,
        1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543,
        1544, 1545, 1546, 1547, 1548, 1549],
       [1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560,
        1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571,
        1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582,
        1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593,
        1594, 1595, 1596, 1597, 1598, 1599],
       [1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610,
        1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621,
        1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632,
        1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643,
        1644, 1645, 1646, 1647, 1648, 1649],
       [1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660,
        1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671,
        1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682,
        1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693,
        1694, 1695, 1696, 1697, 1698, 1699],
       [1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710,
        1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721,
        1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732,
        1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743,
        1744, 1745, 1746, 1747, 1748, 1749],
       [1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760,
        1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771,
        1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782,
        1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793,
        1794, 1795, 1796, 1797, 1798, 1799],
       [1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810,
        1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821,
        1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832,
        1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843,
        1844, 1845, 1846, 1847, 1848, 1849],
       [1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860,
        1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871,
        1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882,
        1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893,
        1894, 1895, 1896, 1897, 1898, 1899],
       [1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
        1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
        1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
        1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
        1944, 1945, 1946, 1947, 1948, 1949],
       [1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
        1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
        1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
        1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
        1994, 1995, 1996, 1997, 1998, 1999],
       [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
        2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
        2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032,
        2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043,
        2044, 2045, 2046, 2047, 2048, 2049],
       [2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060,
        2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071,
        2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082,
        2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093,
        2094, 2095, 2096, 2097, 2098, 2099],
       [2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110,
        2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121,
        2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132,
        2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143,
        2144, 2145, 2146, 2147, 2148, 2149],
       [2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160,
        2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171,
        2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182,
        2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193,
        2194, 2195, 2196, 2197, 2198, 2199],
       [2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210,
        2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221,
        2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232,
        2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243,
        2244, 2245, 2246, 2247, 2248, 2249],
       [2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260,
        2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271,
        2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282,
        2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293,
        2294, 2295, 2296, 2297, 2298, 2299],
       [2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310,
        2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321,
        2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332,
        2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343,
        2344, 2345, 2346, 2347, 2348, 2349],
       [2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360,
        2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371,
        2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382,
        2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393,
        2394, 2395, 2396, 2397, 2398, 2399],
       [2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410,
        2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421,
        2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432,
        2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443,
        2444, 2445, 2446, 2447, 2448, 2449],
       [2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460,
        2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471,
        2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482,
        2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493,
        2494, 2495, 2496, 2497, 2498, 2499]])

## Basic Operations:

##### arithmetic operations - element wise:

In [21]:
h = np.array([20, 30, 40, 50])
i = np.arange(4)
print('h array:\n', h)
print('\ni array:\n', i)

h array:
 [20 30 40 50]

i array:
 [0 1 2 3]

In [22]:
h-i

array([20, 29, 38, 47])

In [23]:
i**2

array([0, 1, 4, 9], dtype=int32)

In [24]:
10*np.sin(h)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [25]:
h<35

array([ True,  True, False, False])

##### * operates element wise:

In [26]:
j = np.array([[1, 1], [0, 1]])
k = np.array([[2, 0], [3, 4]])
print('j array:\n', j)
print('\nk array:\n', k)

j array:
 [[1 1]
 [0 1]]

k array:
 [[2 0]
 [3 4]]

In [27]:
j*k

array([[2, 0],
       [0, 4]])

In [28]:
# matrix product:
j@k

array([[5, 4],
       [3, 4]])

In [29]:
# matris product:
j.dot(k)

array([[5, 4],
       [3, 4]])

In [30]:
rg = np.random.default_rng(1) # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
b = rg.random((2, 3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [32]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [33]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [34]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

##### Many operations (sum, min, max, ...) implemented as methods of ndarray class:

In [35]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [36]:
b.sum()

21.29025228186613

In [37]:
b.min()

3.144159612719634

In [38]:
b.max()

3.950463696325935

In [39]:
l = np.arange(12).reshape(3, 4)
l

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
l.sum(axis=0)

array([12, 15, 18, 21])

In [41]:
l.min(axis=1)

array([0, 4, 8])

In [42]:
l.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## Universal functions:

In [43]:
m = np.arange(10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.exp(m)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [45]:
np.sqrt(m)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Indexing, Slicing, Iterating

###### One-Dimensional

In [46]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [47]:
a[2]

8

In [48]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [49]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [50]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [51]:
for i in a:
    print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998

###### Multidimeansional - one index per array

In [52]:
def f(x, y):
    return 5 * x + y

In [53]:
a = np.fromfunction(f, (5, 4), dtype=int)
a

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [54]:
a[2, 3]

13

In [55]:
a[0:5, 1]

array([ 1,  6, 11, 16, 21])

In [56]:
a[-1]

array([20, 21, 22, 23])

## Shape Manipulation:

In [57]:
a

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [58]:
a = np.floor(10*rg.random((3, 4)))
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [59]:
a.shape

(3, 4)

###### Folowing commands return a modified array / do not change the original:

In [60]:
a.ravel() # flatten array

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [61]:
a.reshape(6, 2)

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.]])

In [62]:
a.T # returns the array, transposed

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

In [63]:
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

###### resize() modifies the original array:

In [64]:
a.resize((2, 6))
a

array([[8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.]])

In [65]:
a.reshape((3, -1))

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

## Stacking together different arrays

In [66]:
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))

In [67]:
a

array([[2., 2.],
       [7., 2.]])

In [68]:
b

array([[4., 9.],
       [9., 7.]])

In [69]:
np.vstack((a, b))

array([[2., 2.],
       [7., 2.],
       [4., 9.],
       [9., 7.]])

In [70]:
np.hstack((a, b))

array([[2., 2., 4., 9.],
       [7., 2., 9., 7.]])

In [71]:
np.column_stack((a, b)) # stacks 1D arrays as columns into a 2D array

array([[2., 2., 4., 9.],
       [7., 2., 9., 7.]])

In [72]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [73]:
a

array([4., 2.])

In [74]:
b

array([3., 8.])

In [75]:
np.column_stack((a, b)) # stacks 1D arrays as columns into a 2D array

array([[4., 3.],
       [2., 8.]])

In [76]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [77]:
np.vstack((a, b))

array([[4., 2.],
       [3., 8.]])

###### row_stack is equivalent to vstack for any input arrays. In fact, row_stack is an alias for vstack

> hstack stacks along their second axes,

> vstack stacks along their first axes, and

> concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

## Splitting one array into several smaller ones

In [78]:
a = np.floor(10*rg.random((2,12)))
a

array([[5., 2., 1., 9., 5., 1., 6., 7., 6., 9., 0., 5.],
       [4., 0., 6., 8., 5., 2., 8., 5., 5., 7., 1., 8.]])

In [79]:
# specifying the number of equally shaped arrays to return:
np.hsplit(a,3) # split into 3

[array([[5., 2., 1., 9.],
        [4., 0., 6., 8.]]),
 array([[5., 1., 6., 7.],
        [5., 2., 8., 5.]]),
 array([[6., 9., 0., 5.],
        [5., 7., 1., 8.]])]

In [80]:
# specifying the columns after which the division should occur:
np.hsplit(a,(3,4)) # Split a after the third and the fourth column

[array([[5., 2., 1.],
        [4., 0., 6.]]),
 array([[9.],
        [8.]]),
 array([[5., 1., 6., 7., 6., 9., 0., 5.],
        [5., 2., 8., 5., 5., 7., 1., 8.]])]

__vsplit__ splits along the vertical axis, and **array_split** allows one to specify along which axis to split

## Copies and Views

## Broadcasting

- how numpy treats arrays with different shapes during arithmetic operations
- the smaller array is “broadcast” across the larger array so that they have compatible shapes
- When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when:
 1. they are equal, or
 2. one of them is 1
 
__The Broadcasting Rule:__
In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.

In [81]:
my_3d_arr = np.arange(70).reshape((2, 7, 5))
my_3d_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [82]:
my_3d_arr * 10

array([[[  0,  10,  20,  30,  40],
        [ 50,  60,  70,  80,  90],
        [100, 110, 120, 130, 140],
        [150, 160, 170, 180, 190],
        [200, 210, 220, 230, 240],
        [250, 260, 270, 280, 290],
        [300, 310, 320, 330, 340]],

       [[350, 360, 370, 380, 390],
        [400, 410, 420, 430, 440],
        [450, 460, 470, 480, 490],
        [500, 510, 520, 530, 540],
        [550, 560, 570, 580, 590],
        [600, 610, 620, 630, 640],
        [650, 660, 670, 680, 690]]])

In [83]:
left_ar = np.arange(6).reshape((2, 3))
right_ar = np.arange(15).reshape((3, -1))

In [84]:
left_ar

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
right_ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
left_ar * right_ar

ValueError: operands could not be broadcast together with shapes (2,3) (3,5)

In [87]:
np.inner(left_ar, right_ar)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [88]:
np.dot(left_ar, right_ar)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

## Advanced indexing and index tricks

Arrays can be indexed by arrays of integers and arrays of booleans

#### Indexing with arrays of Integers

In [89]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [90]:
i = np.array([1, 1, 3, 8, 5, 5])

In [91]:
a[i]

array([ 1,  1,  9, 64, 25, 25], dtype=int32)

###### Multidimensional arrays:

When the indexed array __a__ is multidimensional, a single array of indices refers to the first dimension of **a**

**Ex 1**: converting an image of labels into a color image using a palette:

In [92]:
palette = np.array([[0, 0, 0],        # black
                   [255, 0, 0],       # red
                   [0, 255, 0],       # green
                   [0, 0, 255],       # blue
                   [255, 255, 255]])  # white
image = np.array([[0, 1, 2, 3],       # each value corresponds to a color in the palette
                 [0, 3, 4, 0]])
palette[image]                        # the (2, 4, 3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

The array of indices for each dimmension must hace same shape

In [93]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
i = np.array([[0, 1],   # indices for the first dim of a
             [1, 2]])   

j = np.array([[2, 1],   # indices for the second dimension of a
             [3, 3]])

In [95]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [96]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [97]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [98]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [99]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Ex 2**: search of the maximum value of time-dependent series:

In [100]:
time = np.linspace(20, 145, 5)     # time scale
data = np.sin(np.arange(20)).reshape(5, 4)

In [101]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [102]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [103]:
# index of maxima for each series:
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1], dtype=int64)

In [104]:
# time corresponding to the maxima:
time_max = time[ind]
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [105]:
data_max = data[ind, range(data.shape[1])]  # => data[ind[0],0], data[ind[1], 1] ...
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [106]:
np.all(data_max == data.max(axis=0))

True

###### Indexing with arrays as a target to assign to:

In [109]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [110]:
a[[1, 3, 4]] = 0
a

array([0, 0, 2, 0, 0, 5, 6])

###### ! when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value

In [111]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [112]:
a[[0, 0, 2]] = [1, 2, 3]
a

array([2, 1, 3, 3, 4])

###### Indexing with Boolean Arrays

In [114]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
b = a > 4       # b = boolean with a's shape
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [116]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [117]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

###### Second way of indexing with booleans: similar to integer indexing; for each dimension of the array we give a 1D boolean array selecting the slices we want:

In [119]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
b1 = np.array([False, True, True])
b2 = np.array([True, False, True, False])

In [121]:
a[b1, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
a[b1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
a[:, b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [124]:
a[b1, b2]

array([ 4, 10])

###### The ix_() function:

Used to combine different vectors so as to obtain the result for each n-uplet. For example, if you want to compute all the a+b*c for all the triplets taken from each of the vectors a, b and c:

In [125]:
a = np.array([2, 3, 4, 5])
b = np.array([8, 5, 4])
c = np.array([5, 4, 6, 8, 3])

ax, bx, cx = np.ix_(a, b, c)

In [126]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [127]:
bx

array([[[8],
        [5],
        [4]]])

In [128]:
cx

array([[[5, 4, 6, 8, 3]]])

In [129]:
ax.shape, bx.shape, cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [130]:
result = ax + bx * cx
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])